baseURL = 'https://nlgtEA.github.io/'
languageCode = 'en-us'
title = "TLTC"
theme = "archie"
copyright = "nlgthuan"

pygmentsstyle = "catppuccin-macchiato"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    mode = "auto"

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/nlgthuan"


[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
